# Generated by Django 2.2.16 on 2020-09-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_id', models.CharField(help_text='End SAP id', max_length=18)),
                ('hostname', models.CharField(help_text='Hostname of user', max_length=14)),
                ('loopback', models.CharField(help_text='Loopback interface', max_length=16)),
                ('mac_address', models.CharField(help_text='Mac Address', max_length=17)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
