# Generated by Django 2.2.16 on 2020-09-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='of_type',
            field=models.CharField(choices=[('ag1', 'AG1'), ('css', 'CSS')], default='css', max_length=10),
        ),
    ]
