# Generated by Django 2.2.16 on 2020-09-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_device_of_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='loopback',
            field=models.GenericIPAddressField(verbose_name='Loopback interface'),
        ),
    ]
